runtime: python39
entrypoint: gunicorn -w 4 -b :$PORT main:app

# Set instance class and automatic scaling
instance_class: F2  # Use F2 or a higher class for better performance
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1  # Keep one warm instance to reduce cold starts
  max_instances: 10  # Adjust based on expected traffic

handlers:
# Serve static files (if any)
- url: /static
  static_dir: static

# Default handler for all other routes
- url: /.*
  script: auto
